"""How a club is spelled for the reader, as opposed to how it is stored.

Team identity in this project is a bare string, and it has to stay exactly what
the training CSVs contain: Elo, form, the id cache, every alias table and the
`matches` rows are all keyed on it. That string is inherited from
football-data.co.uk and API-Football, so it is frequently not the club's name —
"Goztep" is Göztepe, "Vfl Bochum" is VfL Bochum, "Vallecano" is Rayo Vallecano.

Renaming the key would mean rewriting 789 CSVs, the id cache and the fixture
table together, and any missed corner would silently split a club in two — the
exact failure the identity audit exists to prevent. So the key is left alone and
the spelling is fixed at the edge: the API applies `display_name` on the way
out, and nothing upstream of that ever sees it.

One-way by design. Nothing looks a club up by its display name, so this map
never has to round-trip.
"""
from __future__ import annotations

# stored key → what the site prints. Absent means the stored name is already
# right, which is true of the large majority.
DISPLAY_NAMES: dict[str, str] = {
    'FC Heidenheim': '1. FC Heidenheim',
    'FC Koln': '1. FC Köln',
    'Horsens': 'AC Horsens',
    'Den Haag': 'ADO Den Haag',
    'AEK': 'AEK Athens',
    'Larisa': 'AEL Larissa',
    'Aarhus': 'AGF Aarhus',
    'Academico Viseu': 'Académico de Viseu',
    'Alaves': 'Alavés',
    'Almeria': 'Almería',
    'Amed': 'Amedspor',
    'Aris': 'Aris Thessaloniki',
    'Ath Bilbao': 'Athletic Bilbao',
    'Ath Madrid': 'Atlético Madrid',
    'Atletico-MG': 'Atlético Mineiro',
    'A. Lustenau': 'Austria Lustenau',
    'Austria Vienna': 'Austria Wien',
    'Bate Borisov': 'BATE Borisov',
    'Buyuksehyr': 'Başakşehir',
    'Besiktas': 'Beşiktaş',
    'Bodo/Glimt': 'Bodø/Glimt',
    "M'gladbach": 'Borussia Mönchengladbach',
    'Sp Braga': 'Braga',
    'Brondby': 'Brøndby',
    'Brest': 'Stade Brestois 29',
    'Celta': 'Celta Vigo',
    'GAP Connah S Quay FC': "Connah's Quay Nomads",
    'Csikszereda M. Ciuc': 'Csíkszereda Miercurea Ciuc',
    'Cadiz': 'Cádiz',
    'La Coruna': 'Deportivo La Coruña',
    'Dila': 'Dila Gori',
    'Dinamo Bucuresti': 'Dinamo București',
    'Djurgarden': 'Djurgården',
    'Drogheda': 'Drogheda United',
    'Dunajska Streda': 'Dunajská Streda',
    'Estac Troyes': 'ESTAC Troyes',
    'Egnatia Rrogozhine': 'Egnatia Rrogozhinë',
    'Ein Frankfurt': 'Eintracht Frankfurt',
    'Espanol': 'Espanyol',
    'Estrela': 'Estrela da Amadora',
    'Europa': 'Europa FC',
    'Eyupspor': 'Eyüpspor',
    'FC Arges': 'FC Argeș',
    'FC Botosani': 'FC Botoșani',
    "Ranger's Andorra": "FC Ranger's",
    'FK Liepaja': 'FK Liepāja',
    'Famalicao': 'Famalicão',
    'Farul Constanta': 'Farul Constanța',
    'Fenerbahce': 'Fenerbahçe',
    'Ferencvarosi TC': 'Ferencváros',
    'For Sittard': 'Fortuna Sittard',
    'Galway': 'Galway United',
    'Gaziantep': 'Gaziantep FK',
    'Genclerbirligi': 'Gençlerbirliği',
    'Gremio': 'Grêmio',
    'Gyori ETO FC': 'Győri ETO FC',
    'Gornik Zabrze': 'Górnik Zabrze',
    'Goztep': 'Göztepe',
    'HB Torshavn': 'HB Tórshavn',
    'Hamburg': 'Hamburger SV',
    'Hegelmann Litauen': 'Hegelmann',
    'Hradec Kralove': 'Hradec Králové',
    'Hacken': 'Häcken',
    'Goteborg': 'IFK Göteborg',
    'Mariehamn': 'IFK Mariehamn',
    'Start': 'IK Start',
    'Iraklis 1908': 'Iraklis',
    'Kasimpasa': 'Kasımpaşa',
    'Kauno Zalgiris': 'Kauno Žalgiris',
    'KI Klaksvik': 'KÍ Klaksvík',
    'Lech Poznan': 'Lech Poznań',
    'Leganes': 'Leganés',
    'Legia': 'Legia Warszawa',
    'Levadeiakos': 'Levadiakos',
    'Lillestrom': 'Lillestrøm',
    'Lommel United': 'Lommel SK',
    'Malmo FF': 'Malmö FF',
    'Man City': 'Manchester City',
    'Man United': 'Manchester United',
    'Maritimo': 'Marítimo',
    'Mjallby': 'Mjällby',
    'Malaga': 'Málaga',
    'Nijmegen': 'NEC Nijmegen',
    'NK Varazdin': 'NK Varaždin',
    'NSI Runavik': 'NSÍ Runavík',
    'Neftchi Baku': 'Neftçi Baku',
    'Nordsjaelland': 'Nordsjælland',
    "Nott'm Forest": 'Nottingham Forest',
    'Kalju Nomme': 'Nõmme Kalju',
    'Odense': 'OB Odense',
    'Otelul': 'Oțelul Galați',
    'Giannina': 'PAS Giannina',
    'Zwolle': 'PEC Zwolle',
    'Paris SG': 'Paris Saint-Germain',
    'Petrolul': 'Petrolul Ploiești',
    'Pogon Szczecin': 'Pogoń Szczecin',
    'Polessya': 'Polissya Zhytomyr',
    'Qarabag': 'Qarabağ',
    'RAAL La Louviere': 'RAAL La Louvière',
    'Salzburg': 'RB Salzburg',
    'Rakow': 'Raków',
    'FC Rapid Bucuresti': 'Rapid București',
    'Vallecano': 'Rayo Vallecano',
    'Betis': 'Real Betis',
    'Sociedad': 'Real Sociedad',
    'Bragantino': 'Red Bull Bragantino',
    'Riga': 'Riga FC',
    'Rigas FS': 'Rīgas FS',
    'Sabah FA': 'Sabah FK',
    'St Etienne': 'Saint-Étienne',
    'Sheffield Weds': 'Sheffield Wednesday',
    'Shkendija': 'Shkëndija',
    'St Truiden': 'Sint-Truiden',
    'Sp Lisbon': 'Sporting CP',
    'St Joseph S Fc': "St Joseph's FC",
    'St. Patricks': "St Patrick's Athletic",
    'Standard': 'Standard Liège',
    'Sao Paulo': 'São Paulo',
    'Sonderjyske': 'SønderjyskE',
    'Tromso': 'Tromsø',
    'US Mondorf-les-bains': 'US Mondorf-les-Bains',
    'St. Gilloise': 'Union Saint-Gilloise',
    'U. Cluj': 'Universitatea Cluj',
    'Univ. Craiova': 'Universitatea Craiova',
    'Valur Reykjavik': 'Valur',
    'Vfl Bochum': 'VfL Bochum',
    'Vitoria': 'Vitória',
    'Vasteras SK': 'Västerås SK',
    'Valerenga': 'Vålerenga',
    'Vikingur Gota': 'Víkingur Gøta',
    'Vikingur Reykjavik': 'Víkingur Reykjavík',
    'Tirol': 'WSG Tirol',
    'Widzew Lodz': 'Widzew Łódź',
    'Wieczysta Krakow': 'Wieczysta Kraków',
    'Wisla': 'Wisła',
    'Wisla Plock': 'Wisła Płock',
    'Zaglebie': 'Zagłębie Lubin',
    'Zira': 'Zirə',
    'Waregem': 'Zulte Waregem',
    'Zurich': 'Zürich',
    'Corum FK': 'Çorum FK',
    'Orgryte': 'Örgryte',
    'Slask Wroclaw': 'Śląsk Wrocław',
    'FK Zalgiris Vilnius': 'Žalgiris Vilnius',
}


def display_name(name: str | None) -> str | None:
    if not name:
        return name
    return DISPLAY_NAMES.get(name, name)


def display_names(names: list[str] | None) -> list[str]:
    return [display_name(n) or n for n in (names or [])]
